// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd_ajRLP5aeElXgB0DzBBPy2Bzg0j-M3o',
    appId: '1:24766627214:web:7b7f7fd76fa6e1b5e2f8df',
    messagingSenderId: '24766627214',
    projectId: 'bene-bono-262c5',
    authDomain: 'bene-bono-262c5.firebaseapp.com',
    storageBucket: 'bene-bono-262c5.appspot.com',
    measurementId: 'G-BZWHWTMZMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvhZaAv7qektYB586EkI965XTGmCEu0FE',
    appId: '1:24766627214:android:7d00222914ab45c5e2f8df',
    messagingSenderId: '24766627214',
    projectId: 'bene-bono-262c5',
    storageBucket: 'bene-bono-262c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPoNkhsup4vy75DQl-3COOeXs5WzdfWgA',
    appId: '1:24766627214:ios:f5ed6276ab567e4ee2f8df',
    messagingSenderId: '24766627214',
    projectId: 'bene-bono-262c5',
    storageBucket: 'bene-bono-262c5.appspot.com',
    iosBundleId: 'com.example.beneBono',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPoNkhsup4vy75DQl-3COOeXs5WzdfWgA',
    appId: '1:24766627214:ios:1745ba559e036b32e2f8df',
    messagingSenderId: '24766627214',
    projectId: 'bene-bono-262c5',
    storageBucket: 'bene-bono-262c5.appspot.com',
    iosBundleId: 'com.example.beneBono.RunnerTests',
  );
}
